/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const SET_LIST_PARAMS = 'SET_LIST_PARAMS';

export const RES_CATAGORIES_FETCHED = 'RES_CATAGORIES_FETCHED';

export const RES_CATAGORY_ADDED = 'RES_CATAGORY_ADDED';

export const RES_CATAGORY_REMOVED = 'RES_CATAGORY_REMOVED';

export const GET_RESOURCE_FETCHED = 'GET_RESOURCE_FETCHED';

export const REMOVE_IMAGE_FROM_UPLOADER = 'REMOVE_IMAGE_FROM_UPLOADER';
